version: 0.2

phases:

  before_install:
    - cd ${TRAVIS_BUILD_DIR}
    - nvm install 16

  install:
    runtime-versions:
      nodejs: 16
      python: 3.9
    commands:
      - npm install

  build:
    commands:
      - npm run build-vue

  post_build:
    commands:
      - chmod 755 ./scripts/*.sh
      - ./scripts/codebuild/create-build-summary.sh

artifacts:
  files:
  - '.ebextensions/**/*'
  - '.platform/**/*'
  - 'app/**/*'
  - 'application.py'
  - 'config/**/*'
  - 'consoler.py'
  - 'diablo/**/*'
  - 'dist/**/*'
  - 'fixtures/**/*'
  - 'requirements.txt'
  - 'scripts/**/*'
